foodchallenge/urls.py
from core import views
from django.contrib import admin
from django.urls import path, include
from core.views import SignUpClientView, SignUpBusinessView


urlpatterns = [
    path('', views.home, name='home'),
    path('search/', views.search, name='search'),
    path('select/<int:challenge_id>/', views.select, name='select'),
    path('admin/', admin.site.urls),
    path('business-sign_up/', SignUpBusinessView.as_view(), name="business_create"),
    path('client-sign_up/', SignUpClientView.as_view(), name="client_create"),
    path('profile/<int:client>', views.profile, name="profile"),
    path('about_me/', views.about_me, name="about_me"),
    path('accounts/', include("django.contrib.auth.urls")),
]

core/models.py
from django.conf import settings
from django.contrib.auth.models import User
from django.db import models


class Challenge(models.Model):
    name = models.CharField(max_length=200)
    summary = models.CharField(max_length=200)
    description = models.TextField()

    class Level(models.IntegerChoices):
        EASY = 1, "easy"
        MEDIUM = 2, "medium"
        HARD = 3, "hard"
        EXTREME = 4, "extreme"

    level = models.IntegerField(choices=Level.choices)

    def __str__(self):
        return f"{self.name}"


class WorkDay(models.Model):
    day = models.CharField(default="", max_length=15)

    def __str__(self):
        return self.day


class TheTypeOfFood(models.Model):
    title = models.CharField(max_length=100)


class Business(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='business',
                                default=None)
    phone = models.CharField(max_length=50, null=True, blank=True)
    description = models.TextField()
    days = models.ManyToManyField(WorkDay, blank=True)
    location = models.CharField(max_length=20)
    start_hour = models.TimeField(default="08:00")
    end_hour = models.TimeField(default="16:00")
    TheTypeOfFood = models.ManyToManyField(TheTypeOfFood, blank=True)

    def __str__(self):
        return self.user.username


class Client(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='client')

    def __str__(self):
        return self.user.username


class UserInChallenge(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE, related_name='userChallenge')
    challenge = models.ForeignKey(Challenge, on_delete=models.CASCADE, related_name='userChallenge')

core/forms.py
import datetime
from django import forms
from django.utils import timezone

from core.models import Business


class SignUpBusinessForm(forms.ModelForm):
    username = forms.CharField(
        label='User name',
        max_length=200, widget=forms.TextInput(attrs={'class': 'from-control'}))
    first_name = forms.CharField(label='first_name', max_length=100)
    email = forms.EmailField(label='Email', max_length=200)
    password = forms.CharField(label='Password', max_length=200, widget=forms.PasswordInput)

    class Meta:
        model = Business
        fields = ['username', 'location', 'description', 'email', 'password',
                  'days', 'start_hour', 'end_hour']
        widgets = {
            'start_hour': forms.Select(
                attrs={'class': 'from-control'},
                choices=((f'{x}:00', f'{x}:00') for x in range(6, 24))),
            'end_hour': forms.Select(choices=((f'{x}:00', f'{x}:00') for x in range(6, 24)))
        }


class SignUpClientForm(forms.Form):
    username = forms.CharField(
        label='User name',
        max_length=200, widget=forms.TextInput(attrs={'class': 'from-control'}))

    email = forms.EmailField(label='Email', max_length=200)
    password = forms.CharField(label='Password', max_length=200, widget=forms.PasswordInput)


class NameForm(forms.Form):
    c = forms.CharField(label='/', max_length=100)

core/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render

from .forms import NameForm
from django.contrib import auth
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import AccessMixin
from django.contrib.auth.models import User
from django.db.models import Q
from django.http import Http404
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import FormView

from .forms import SignUpClientForm, SignUpBusinessForm
from .models import Challenge, Client, Business, UserInChallenge


def home(request):
    c = Challenge.objects.all().order_by('?')
    d = {'object_list': c}
    return render(request, 'core/home.html', d)


# @login_required
def search(request):
    q = request.GET.get('q')
    c = Challenge.objects.filter(Q(name__icontains=q) | Q(summary__icontains=q) | Q(description__icontains=q))
    for n in c:
        if request.user.is_authenticated:
            n.in_challenge = UserInChallenge.objects.filter(
                client=request.user.client,
                challenge_id=n.id
            ).exists()

    context = {'object_list': c}
    return render(request, 'core/search.html', context)


# @login_required
def select(request, challenge_id):
    c = Challenge.objects.get(id=challenge_id)
    in_challenge = False
    if request.user.is_authenticated:
        in_challenge = UserInChallenge.objects.filter(
            client=request.user.client,
            challenge_id=challenge_id
        ).exists()
    if request.method == 'POST':
        UserInChallenge.objects.create(
            client=request.user.client,
            challenge_id=challenge_id
        )
        in_challenge = True
    challenge_list = [
        "Chinese food challenge",
        "Vegan Instant",
        "Food Diggers",
        "Indian food challenge",
        "Special challenge for a limited time",
        "Jerusalem Challenge",
        "The Shawarma Challenge",
    ]
    context = {'object': c, 'in_challenge': in_challenge}
    return render(request, 'core/challenge_page.html', context)


class NoneLoginPermitted(AccessMixin):
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            raise Http404
        return super().dispatch(request, *args, **kwargs)


class SignUpClientView(NoneLoginPermitted, FormView):
    template_name = 'registration/signup_client.html'
    form_class = SignUpClientForm
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        data = form.cleaned_data
        user = User.objects.create(
            username=data['username'],
            email=data['email'],
        )
        user.set_password(data['password'])
        user.save()
        Client.objects.create(
            user=user,
        )
        login(self.request, user)
        return super(SignUpClientView, self).form_valid(form)


class SignUpBusinessView(FormView):
    template_name = 'registration/signup_business.html'
    form_class = SignUpBusinessForm
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        data = form.cleaned_data
        user = User.objects.create(
            username=data['username'],
            first_name=data['first_name'],
            email=data['email'],
        )
        user.set_password(data['password'])
        user.save()
        business = Business.objects.create(
            user=user,

            location=data['location'],
            description=data['description'],
            start_hour=data['start_hour'],
            end_hour=data['end_hour']
        )
        business.days.set(data['days']),
        business.save()
        login(self.request, user)
        return super(SignUpBusinessView, self).form_valid(form)


def profile(request, client):
    challenge = UserInChallenge.objects.filter(client__user_id=client)
    return render(request, 'core/fixed_profile.html', {'client': Client.objects.get(user_id=client), 'challenge': challenge})

def about_me(request):
    return render(request, 'core/about_me.html')

def admin_page(request):
    if not request.user.is_authenticated():
        return redirect('blog_login')

    return render(request, 'home.html')

core/templates/core/_header.html
sdfsdfdsfsd

core/templates/core/about_me.html
{% extends 'core/base.html' %}
{% block content %}
    <div class="containers">
        <h5>Hey I'm Shani!</h5>
        <p>One of my favorite hobbies is food!!! </p>
        <p>I've found that for most of the time, we compromise and eat the same dish over and over again.</p>
        <p>So I decided to share with you my hobby that I love and show the best and delicious places I discover in a fun
            way.</p>
        <p>I hope you will enjoy,</p>
        <p>with love and joy,</p>
        <p>Shani 🤍</p>

    </div>
{% endblock %}

core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Food Challenge</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block extracss %}{% endblock %}
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'home' %}">FoodChallenge</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
         <li class="nav-item">
                <a class="nav-link" href="{% url 'about_me' %}">About Me</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'profile' user.id %}">Profile</a>
            </li>
            {% endif %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Challenges
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    {% for challenge in challenge_list %}
                    <a class="dropdown-item" href="{% url 'select' forloop.counter %}">{{ challenge }}</a>
                    {% endfor %}
                </div>
            </li>
            {% if user.is_authenticated %}
                <li class="nav-item logout">
                    <a class="nav-link" href="{% url 'logout' %}">logout</a>
                </li>
            {% endif %}
            {% if not user.is_authenticated %}
                <li class="nav-item login">
                    <a class="nav-link" href="{% url 'login' %}">login</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>
{% block content %}{% endblock %}
{% block scripts %}
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
            integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
            integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
            crossorigin="anonymous"></script>
    <script src="{% static 'js/script.js' %}"></script>
{% endblock %}
</body>
</html>

core/templates/core/challenge_page.html
{% extends 'core/base.html' %}

{% block content %}
    <div class="challengePage">
        <div class="containers">
            <h2>{{ object.name }}</h2>
            <p>Difficulty: {{ object.get_level_display }}</p>
            <p class="description">{{ object.description }}</p>
            {% if user.is_authenticated %}
                {% if not in_challenge %}
                    <form method="post">
                        {% csrf_token %}
                        <input type="submit" value="START">
                    </form>
                {% else %}
                    <p>you already in challenge</p>
                {% endif %}
            {% else %}
                <a>If you want to start the challenge please click on</a>
                <a class="btn btn-login" href="{% url 'login' %}">LOGIN</a><a> if you are not registered click on</a>
                <a class="btn btn-signup " href="{% url 'client_create' %}">SIGNUP </a>
            {% endif %}
        </div>
    </div>
{% endblock %}

core/templates/core/fixed_profile.html
{% extends 'core/base.html' %}
{% block content %}
<div class="containers">
    <h5>{{ client.user.username }}</h5>
    <p>Currently attending in {{ challenge|length }}  challenges</p>
        <p>Yours challenges:</p>
    {% for c in challenge %}
        <p>{{ c.challenge.name }}  </p>
    {% endfor %}
</div>
{% endblock %}

core/templates/core/fixed_propile.html
{% extends 'core/base.html' %}
{% block content %}
<div class="containers">
    <h5>user name</h5>
    <h6>user status</h6>
    <h6>user point</h6>
    <p>currently attending in (number) challenges</p>
    <p>information on the challenges </p>
</div>
{% endblock %}

core/templates/core/home.html
{% extends 'core/base.html' %}

{% block content %}
    <div class="homePage">
    <div class="containers">
        <div class="header">
            <h1>Food Challenge</h1>
        </div>
        <form class="form-inline" action="{% url 'search' %}">
            <div class="form-group mb-2">
                <label for="search" class="sr-only">Keyword</label>
                <input type="search" class="form-control" id="search" name="q">
            </div>

            <button class="btn btn-home" type="submit">Search</button>
        </form>

        {#            <div class="row kill-margin ">#}
        <div class="row kill-margin">
            {% for c in object_list %}
                <div class="card col-xs-12 col-sm-12 col-md-6 col-lg-4">
                <div class="card-body">
                    <h5 class="card-title">{{ c.name }}</h5>
                    <p class="card-text">{{ c.summary }}.</p>
                    <p class="card-text"><small class="text-muted">Difficulty: {{ c.get_level_display }}</small></p>
                    <a href="{% url 'select' c.id %}" class="card-link">for more information</a>
                </div>
                </div>

            {% endfor %}
            </div>

        </div>
    </div>
{% endblock %}

core/templates/core/search.html
{% extends 'core/base.html' %}

{% block content %}
    <div class="searchPage">
        <div class="containers">
            {% for c in object_list %}
                <h2>{{ c.name }}</h2>
                <p>Difficulty: {{ c.get_level_display }}</p>
                <p class="description">{{ c.description }}</p>
                {% if user.is_authenticated %}
                    {% if not c.in_challenge %}
                        <form method="post">
                            {% csrf_token %}
                            <input type="submit" value="START">
                        </form>
                    {% else %}
                        <p>you already in challenge</p>
                    {% endif %}
                {% else %}
                    <a>If you want to start the challenge please click on</a>
                    <a class="btn btn-login" href="{% url 'login' %}">LOGIN</a>
                    <a> if you are not registered click on</a>
                    <a class="btn btn-signup " href="{% url 'client_create' %}">SIGNUP </a>
                {% endif %}
            {% endfor %}
        </div>
    </div>
{% endblock %}